web_port: 5000

mqtt:
  host: mqtt.server.com
  topic_prefix: frigate
#  user: username # Optional -- Uncomment for use
#  password: password # Optional -- Uncomment for use

cameras:
  back:
    rtsp:
      protocol: rtsps
      host: 54.201.101.106
      port: 1443
      path: 6E57B41D2097DC95C46367921B2CEFB5.sdp 
      # values that begin with a "$" will be replaced with environment variable
    mask: back-mask.bmp
    regions:
      - size: 350
        x_offset: 0
        y_offset: 300
        min_person_area: 5000
        threshold: 0.5
      - size: 400
        x_offset: 350
        y_offset: 250
        min_person_area: 2000
        threshold: 0.5
      - size: 400
        x_offset: 750
        y_offset: 250
        min_person_area: 2000
        threshold: 0.5
