web_port: 5000

mqtt:
  host: 192.168.50.228
  topic_prefix: frigate
  user: ha # Optional -- Uncomment for use
  password: luckposht # Optional -- Uncomment for use

cameras:
  back:
    rtsp:
      protocol: rtsps
      host: 18.237.1.75
      port: 1443
      path: 6F940C592A6B130209FE2BF59D547208.sdp 
      # values that begin with a "$" will be replaced with environment variable
    ##mask: back-mask.bmp
    regions:
      - size: 350
        x_offset: 0
        y_offset: 300
        min_person_area: 5000
        threshold: 0.5
      - size: 400
        x_offset: 350
        y_offset: 250
        min_person_area: 2000
        threshold: 0.5
      - size: 400
        x_offset: 750
        y_offset: 250
        min_person_area: 2000
        threshold: 0.5
  front:
    rtsp:
      protocol: rtsps
      host: 54.201.101.106
      port: 1443
      path: 6E57B41D2097DC95C46367921B2CEFB5.sdp
      # values that begin with a "$" will be replaced with environment variable
    ##mask: back-mask.bmp
    regions:
      - size: 1000 
        x_offset: 300
        y_offset: 00
        min_person_area: 500
        threshold: 0.4

  
